# If you need help, please visit wiki page > https://github.com/Jakubson/JPremium/wiki
settings:
    mysql:
        host: 127.0.0.1
        port: 3306
        user: root
        password: password
        database: jpremium
        first-table: # Change columns names do not produce change columns names in already created tables in MySQL!
            name: non_premium_users
            columns:
                nickname: nickname
                index: index
                password: password
                language: language
                ip: ip
        second-table: # Change columns names do not produce change columns names in already created tables in MySQL!
            name: premium_users
            columns:
                uuid: uuid
                index: index
                language: language
        use-ssl: true
        use-sqlite: false # You have to install this plugin on your BungeeCord server: https://www.spigotmc.org/resources/57191/
    secret-key: none # Your server secret key, please enter this same key to config in JPremium config file on the Spigot servers.
    default-skin: Jakubson # This player's skin set to all cracked players. Works only if 'fixed-unique-id' is enable. If you want to turn off it, please set empty value.
    boss-bar-color: 3 # Color of boss bar. (0 - pink, 1 - blue, 2 - red, 3 - green, 4 - yellow, 5 - purple, 6 - white)
    boss-bar-division: 2 # Division of boss bar. (0 - no division, 1 - 6 notches, 2 - 10 notches, 3 - 12 notches, 4 - 20 notches)
    max-ip-accounts: 2 # How many non-premium players can register with this same ip address.
    fixed-unique-id: true # Whether to use random unique id for player. I recommend turn on it.
    default-language: en # Default language from messages section.
    registration-type: SERVER # Whether to allow register non-premium players on the server, website or both sites. (SERVER, WEBSITE, SERVER_AND_WEBSITE, SECURE - if to server joined more than 25 players in 3 minutes, next new players must register via website)
    disable-auto-login: true # Whether premium player can disable auto login.
    auto-login-premium: false # Whether to auto login new premium players.
    switch-server-timeout: 200 # How many the plugin must wait in order to connect player with another server. Change this value only when author of JPremium ask for it.
    allow-nickname-pattern: '[a-zA-Z0-9_]{3,16}' # Regex pattern of allow nickname.
    enable-allow-address: false # Whether to check address which player using to connect to the server.
    case-sensitive-allow-address: true # Whether to check case sensitive of allow addresses.
    allow-addresses: # Using only these addresses player can join to the server.
      - example.com
      - mc.example.com
    staff-addresses: # Using only these addresses player with 'jpremium.staff' permission can join to the server.
      - admin.example.com
    login:
        commands:
            - login
            - l
        server: # Server names to which non-premium player connect in order to login.
            - authorisation
        after: # Server names to which non-premium or premium player connect after login.
            - lobby
        time: 20 # How many time has non-premium player to login.
        kick-when-bad-password: false # Whether to kick non-premium player when he enter wrong password.
    register:
        commands:
            - register
            - r
        server: # Server names to which non-premium player connect in order to register.
            - authorisation
        after: # Server names to which non-premium player connect after register.
            - lobby
        time: 60 # How many time has non-premium player to register.
        password-min-length: 5 # What is the minimum number of characters in the password
        password-max-length: 30 # What is the maximal number of characters in the password
        case-sensitive-bad-passwords: true # Whether to check case sensitive of bad passwords.
        bad-passwords: # The passwords are considered as unsafe and non-premium player cannot set they as password.
            - 12345
            - qwerty
            - abcdef
        captcha: true # Whether to non-premium player must enter captcha code during register.
        captcha-length: 6 # The length of captcha code. Maximal length is 32.
    unregister:
        commands:
            - unregister
    auto-login:
        commands:
            - autologin
    change-password:
        commands:
            - changepassword
    change-language:
        commands:
            - language
    jpremium-register:
        commands:
            - jregister
    jpremium-unregister:
        commands:
            - junregister
    jpremium-auto-login:
        commands:
            - jautologin
    jpremium-change-password:
        commands:
            - jchangepassword
    jpremium-change-language:
        commands:
            - jlanguage
    jpremium-change-skin:
        commands:
            - jskin
    jpremium-verify:
        commands:
            - jverify
    jpremium-players:
        commands:
            - jplayers
    jpremium-convert:
        commands:
            - jconvert
messages:
    en:
        servers-not-responding: '&c&l# &7We cannot authorize your account at the moment! Please try again in a few minutes!'
        max-ip-accounts: '&c&l# &7You cannot register more accounts using your IP address!'
        website-registration: '&a&l# &7You have to register your account on &amc.example.com&7!'
        update: '&a&l# &7There is a new update of JPremium, please download now from &ahttps://www.spigotmc.org/resources/27766/&7!'
        disallow-nickname: '&c&l# &7You cannot use your nickname on this server! Please try use another nickname!'
        disallow-address: '&c&l# &7You cannot join to the server using this address! Please use &amc.example.com &7address!'
        disallow-staff-address: '&c&l# &7This account requires a special server IP address to connect with it! Please contact with the server staff!'
        boss-bar: '&a&l* &7mc.example.com &a&l*'
        premium:
            fadeIn: 1
            stay: 3
            fadeOut: 1
            title: '&a&l* &7Hi, &o%PLAYER_NAME% &a&l*'
            subtitle: '&7You have a premium account!'
            header: ''
            footer: ''
            chat: |
                &f
                &a # INFO #
                &f
                &7If you want to switch your account to non-premium,
                &7please execute:
                &f
                &a  /autologin &o<new password> <re-new password>
                &f
                &7In any moment you can come back to premium
                &7account by execute (without arguments):
                &f
                &a  /autologin
                &f
                &7Do not be afraid of! You will keep your inventory,
                &7stats, ranks, permission and etc!
                &f
        non-premium:
            login:
                before:
                    fadeIn: 1
                    stay: 18
                    fadeOut: 1
                    title: '&a&l* &7Please login with  &a&l*'
                    subtitle: '&a/login &o<password>'
                    header: ''
                    footer: ''
                    chat:
                after:
                    fadeIn: 1
                    stay: 3
                    fadeOut: 1
                    title: '&a&l* &7Hi, &o%PLAYER_NAME% &a&l*'
                    subtitle: '&7You have logged'
                    header: ''
                    footer: ''
                    chat: |
                        &f
                        &a # INFO #
                        &f
                        &7If you want to chnage your account
                        &7password please execute:
                        &f
                        &a  /changepassword &o<old password> <new password> <re-new password>
                        &f
                error:
                    timeout: '&c&l# &7The time to login was elapsed! Please try again!'
                    registered: '&c&l# &7You have to register your account to use that command!'
                    logged: '&c&l# &7You are already logged!'
                    enter-password: '&c&l# &7!You have not entered all arguments! Please enter password!'
                    incorrect-password: '&c&l# &7You have entered incorrect password! Please enter correct password!'
                    incorrect-nickname: '&c&l# &7You use incorrect nickname! Please use &a%PLAYER_CORRECT_NAME%&7, not &c%PLAYER_NAME%&7!'
            register:
                before:
                    fadeIn: 1
                    stay: 58
                    fadeOut: 1
                    title: '&a&l* &7Please register with &a&l*'
                    subtitle: '&a/register &o<password> <re-password> <captcha>'
                    header: ''
                    footer: ''
                    chat: ''
                after:
                    fadeIn: 1
                    stay: 3
                    fadeOut: 1
                    title: '&a&l* &7Hi, &o%PLAYER_NAME% &a&l*'
                    subtitle: '&7You have registered!'
                    header: ''
                    footer: ''
                    chat: ''
                captcha: '&a&l* &7Your captcha code is &a%CAPTCHA% &a&l*'
                premium: |
                    &f
                    &a # INFO #
                    &f
                    &7Authorization plugin has detected that
                    &7you are using a premium nickname!
                    &7If you have a premium luncher and you do not
                    &7want to login every time when you join to
                    &7the server, please execute (without arguments):
                    &f
                    &a  /autologin
                    &f
                    &7Do not execute that command when you have
                    &7a cracked luncher because you lose your account!
                    &7
                error:
                    timeout: '&c&l# &7The time to register was elapsed! Please try again!'
                    registered: '&c&l# &7You are already registered!'
                    enter-passwords: '&c&l# &7You have not entered all arguments! Please enter password, re-password and captcha!'
                    password-too-short: '&c&l# &7You have entered too short password! Please enter longer password!'
                    password-too-long: '&c&l# &7You have entered too long password! Please enter shorter password!'
                    password-bad: '&c&l# &7The password is too weak! Please enter stronger password!'
                    passwords-same: '&c&l# &7You have entered two different passwords! Please enter the same passwords!'
                    incorrect-captcha: '&c&l# &7You have entered incorrect captcha! Please enter captcha which is on the top of your screen!'
            unregister:
                after: '&a&l# &7Your account has been unregistered!'
                error:
                    premium: '&c&l# &7The premium players cannot use that command!'
                    enter-password: '&c&l# &7You have not entered all arguments! Please a enter password!'
                    incorrect-password: '&c&l# &7You have entered incorrect password! Please enter an correct password!'
            auto-login:
                after:
                    premium: '&a&l# &7You have switched your account to a premium! You do not need use login command now!!'
                    password: '&a&l# &7You have switched your account to a non-premium! You need use login command now!'
                error:
                    premium: '&c&l# &7The non-premium players cannot use that command!'
                    disable-auto-login: '&c&l# &7You cannot switch your account to non-premium player!'
                    enter-passwords: '&c&l# &7You have not entered all arguments! Please enter a password, re-password!'
                    password-too-short: '&c&l# &7You have entered too short password! Please enter longer password!'
                    password-too-long: '&c&l# &7You have entered too long password! Please enter shorter password!'
                    password-bad: '&c&l# &7The password is too weak! Please enter stronger password!'
                    passwords-same: '&c&l# &7You have entered two different passwords! Please enter the same passwords!'
            change-password:
                after:
                    fadeIn: 0
                    stay: 0
                    fadeOut: 0
                    title: ''
                    subtitle: ''
                    header: ''
                    footer: ''
                    chat: '&a&l# &7Your password has been changed!'
                error:
                    premium: '&c&l# &7The premium players cannot use that command!'
                    enter-passwords: '&c&l# &7You have not entered all arguments! Please enter an old password, a new password, re-new-password!'
                    incorrect-old-password: '&c&l# &7You have entered incorrect old password! Please enter old correct password!'
                    passwords-same: '&c&l# &7You have entered two different new passwords! Please enter the same passwords!'
            change-language:
                after:
                    fadeIn: 0
                    stay: 0
                    fadeOut: 0
                    title: ''
                    subtitle: ''
                    header: ''
                    footer: ''
                    chat: '&a&l# &7Your language has been changed!'
                error:
                    enter-language: '&c&l# &7You have not entered all arguments! Please enter a language!'
                    incorrect-language: '&c&l# &7You have entered incorrect language name! Please enter correct language!'
            jpremium-register:
                after: '&a&l# &&You have register that user!'
                error:
                    enter-nickname-and-password: '&c&l# &7You have not entered all arguments! Please enter nickname and password!'
                    user-is-exist: '&c&l# &7That user is already registered!'
            jpremium-unregister:
                after:
                    user-kick: '&a&l# &7Your account has been unregistered'
                    unregistered: '&a&l# &7You have unregistered that user!'
                error:
                    enter-nickname: '&c&l# &7You have not entered all arguments! Please enter nickname!'
                    user-is-not-exist: '&c&l# &7That user is not registered!'
                    user-is-premium: '&c&l# &7You cannot unregister that user because it is premium!'
                    user-is-not-registered: '&c&l# &7That user is not registered!'
            jpremium-auto-login:
                after:
                    turned-auto-login: '&a&l# &&You have switched the account of that user to premium!'
                    turned-password: '&a&l# &7You have switched the account of that user to non-premium!'
                    kick-message-turned-auto-login: '&a&l# &7You have switched your account to a premium! You do not need use login command now!!'
                    kick-message-turned-password: '&a&l# &7You have switched your account to a non-premium! You need use login command now!'
                error:
                    enter-nickname: '&c&l# &7You have not entered all arguments! Please enter nickname!'
                    enter-nickname-and-password: '&c&l# &7You have not entered all arguments! Please enter nickname and password!'
                    user-is-not-premium: '&c&l# &7You cannot switch the account of that user for premium because it is non-premium!'
                    user-is-not-exits: '&c&l# &7That user is not registered!'
            jpremium-change-password:
                after:
                    user-kick: '&a&l# &7Your password has been changed!'
                    password-changed: '&a&l# &7You have changed the password of that user!'
                error:
                    enter-nickname-and-password: '&c&l# &7You have not entered all arguments! Please enter nickname and password!'
                    user-is-not-exist: '&c&l# &7That user is not registered!'
                    user-is-premium: '&c&l# &7You cannot change that user password because it is premium!'
                    user-is-not-registered: '&c&l# &7That user is not registered!'
            jpremium-change-language:
                after:
                    user-changed:
                        fadeIn: 0
                        stay: 0
                        fadeOut: 0
                        title: ''
                        subtitle: ''
                        header: ''
                        footer: ''
                        chat: '&a&l# &7Your language has been changed!'
                    language-changed: '&a&l# &7You have changed the language of that user!'
                error:
                    enter-nickname-and-language: '&c&l# &7You have not entered all arguments! Please enter nickname and language!'
                    user-is-not-exist: '&c&l# &7That user is not registered!'
                    user-is-not-registered: '&c&l# &7That user is not registered!'
                    incorrect-language: '&c&l# &7You have entered incorrect language name! Please enter correct language!'
            jpremium-change-skin:
                after:
                    user-changed: '&a&l# &7You skin has been changed! To see result, please re-join to the server!'
                    skin-changed: '&a&l# &7You have changed the skin of that user!'
                error:
                    wait: '&a&l# &7Servers are processing your request! Please wait!'
                    eneter-nickname-and-skin: '&c&l# &7You have not entered all arguments! Please enter nickname itself (to restart skin) or nickname and skin nickname (to set a new skin)!'
                    too-many-requests: '&c&l# &7You can use that command every 5 minutes!'
                    skin-is-not-exits: '&c&l# &7That skin is not exits!'
            jpremium-verify:
                after:
                    premium: '&a&l# &7That user is premium!'
                    non-premium: '&a&l# &7That user is non-premium!'
                error:
                    enter-nickname: '&c&l# &7You have not entered all arguments! Please enter nickname!'
                    user-is-not-exist: '&c&l# &7That user is not registered!'
            jpremium-players:
                after:
                    separator: '&a&l* &7-------------------- &a&l*'
                    list: '&a&l%NUMBER%&8. &a%PLAYER_CORRECT_NAME% &8/ &7%PLAYER_LANGUAGE% &8/ &7%PLAYER_IP%'
                error:
                    enter-min-max: '&c&l# &7You have not entered all arguments! Please enter minimum and maximum numbers of players!'
                    invalid-quantity: '&c&l# &7You have entered incorrect quantity of players! Minimum argument must be greatest that 0 and smaller than maximum argument! Maximum argument must be equal of smaller that %MAX%!'
