settings:
    mysql:
        host: 127.0.0.1
        port: 3306
        user: root
        password: password
        database: jpremium
        first-table: non_premium_users
        second-table: premium_users
        use-ssl: true
    use-proxy: false # Whether to use proxies to connect with Mojang servers. If you have server where is more than 500 players, I recommend turn on this.
    secret-key: none # Your server secret key, please enter this same key to config in JPremium config file on the Spigot servers.
    max-ip-accounts: 2 # How many non-premium players can register with this same ip address.
    max-connections: 15 # How many players can join to the server within 30 seconds.
    fixed-unique-id: true # Whether to use random unique id for player. I recommend turn on it.
    default-language: en # Default language from messages section.
    registration-type: SERVER # Whether to allow register non-premium players on the server, website or both sites.
    disable-auto-login: true # Whether premium player can disable auto login.
    auto-login-premium: true # Whether to auto login new premium players.
    switch-server-timeout: 200 # How many the plugin must wait in order to connect player with another server. Change this value only when author of JPremium ask for it.
    enable-allow-address: false # Whether to check address which player using to connect to the server.
    case-sensitive-allow-address: true # Whether to check case sensitive of allow addresses.
    allow-addresses: # Using only these addresses player can join to the server.
      - 127.0.0.1
      - localhost
      - example.com
      - mc.example.com
    staff-addresses: # Using only these addresses player with 'jpremium.staff' permission can join to the server.
      - admin.example.com
    login:
        commands: # Login command aliases. The first command is main command.
            - login
            - l
        server: # Server names to which non-premium player connect in order to login.
            - login1
            - login2
        after: # Server names to which non-premium and premium player connect after login.
            - lobby1
            - lobby2
        time: 20 # How many time has non-premium player to login.
        kick-when-bad-password: false # Whether to kick non-premium player when he enter wrong password.
    register:
        commands: # Register command aliases. The first command is main command.
            - register
            - r
        server: # Server names to which non-premium player connect in order to register.
            - login1
            - login2
        after: # Server names to which non-premium player connect after register.
            - lobby1
            - lobby2
        time: 60 # How many time has non-premium player to register.
        password-min-length: 5 # What is the minimum number of characters in the password
        password-max-length: 30 # What is the maximal number of characters in the password
        case-sensitive-bad-passwords: true # Whether to check case sensitive of bad passwords.
        bad-passwords: # The passwords are considered as unsafe and non-premium player cannot set they as password.
            - 12345
            - qwerty
            - abcdef
        captcha: true # Whether to non-premium player must enter captcha code during register.
        captcha-length: 6 # The length of captcha code. Maximal length is 32.
    unregister:
        commands: # Unregister command aliases.
            - unregister
            - unreg
    auto-login:
        commands: # Auto login command aliases.
            - autologin
            - al
    change-password:
        commands: # Change password command aliases.
            - changepassword
            - change
    change-language:
        commands: # Change language command aliases.
            - language
            - lang
    jpremium-register:
        commands: # Register admin command aliases.
            - jregister
            - jreg
    jpremium-unregister:
        commands: # Unregister admin command aliases.
            - junregister
            - junreg
    jpremium-change-password:
        commands: # Change password admin command aliases.
            - jchangepassword
            - jchpass
    jpremium-change-language:
        commands: # Change language admin command aliases.
            - jlanguage
            - jlang
    jpremium-verify:
        commands: # Verify admin command aliases.
            - jverify
            - jver
messages:
    en:
        servers-not-responding: '&c&lError! &cAuthentication servers do not respond, we can not verify your account!'
        max-ip-accounts: '&c&lError! &cYour ip address has already been registered with the maximum number of accounts!'
        max-connections: '&c&lError! &cToo many players want to connection to the server now! Please wait and try again!'
        website-registration: '&a&lWebsite registration! &aPlease visit www.example.com/register to register your account!'
        update: '&a&lJPremium update! &aA new version of plugin! Download now from https://www.spigotmc.org/resources/jpremium.27766/'
        disallow-address: '&c&lDisallow address! &cPlease connect to server using example.com address!'
        disallow-staff-address: '&c&lDisallow address! &cPlease connect to server using example.com address!'
        boss-bar: '&a&lHello %PLAYER_NAME%, You are playing on the &6&lEXAMPLE.COM&a&l!'
        premium:
            fadeIn: 1
            stay: 3
            fadeOut: 1
            title: '&a&lWelcome %PLAYER_NAME%!'
            subtitle: '&aYou has logged by premium account!'
            header: |-
                &f
                &a&lWelcome %PLAYER_NAME%!
                &f
            footer: |-
                &f
                &aYou has logged by premium account!
                &f
            chat: |-
                &f
                &a&lWelcome %PLAYER_NAME%!
                &aYou has logged by premium account!
                &f
        non-premium:
            login:
                before:
                    fadeIn: 1
                    stay: 18
                    fadeOut: 1
                    title: '&e&lPlease login using:'
                    subtitle: '&6/login <password>'
                    header: |-
                        &f
                        &e&lPlease login using:
                        &f
                    footer: |-
                        &f
                        &6/login <password>
                        &f
                    chat: ''
                after:
                    fadeIn: 1
                    stay: 3
                    fadeOut: 1
                    title: '&a&lWelcome %PLAYER_NAME%!'
                    subtitle: '&aYou has logged by non-premium account!'
                    header: |-
                        &f
                        &a&lWelcome %PLAYER_NAME%!
                        &f
                    footer: |-
                        &f
                        &aYou has logged by non-premium account!
                        &f
                    chat: |-
                        &f
                        &a&lWelcome %PLAYER_NAME%!
                        &aYou has logged by non-premium account!
                        &f
                error:
                    timeout: '&c&lTimeout! &cJoin to the server and try again!'
                    registered: '&c&lRegistered! &cYou must registered to login!'
                    logged: '&c&lLogged! &cYou are already logged!'
                    enter-password: '&c&lInvalid arguments! &cEnter password and try again!'
                    incorrect-password: '&c&lIncorrect password! &cEnter correct password and try again!'
                    incorrect-nickname: '&c&lIncorrect nickname! &cLogin with %PLAYER_CORRECT_NAME% player name, not with %PLAYER_NAME%!'
            register:
                before:
                    fadeIn: 1
                    stay: 28
                    fadeOut: 1
                    title: '&e&lPlease register using:'
                    subtitle: '&6/register <password> <re-password> <captcha>'
                    header: |-
                        &f
                        &e&lPlease register using:
                        &f
                    footer: |-
                        &f
                        &6/register <password> <re-password> <captcha>
                        &f
                    chat: ''
                after:
                    fadeIn: 1
                    stay: 3
                    fadeOut: 1
                    title: '&a&lWelcome %PLAYER_NAME%!'
                    subtitle: '&aYou has logged by non-premium account!'
                    header: |-
                        &f
                        &a&lWelcome %PLAYER_NAME%!
                        &f
                    footer: |-
                        &f
                        &aYou has logged by non-premium account!
                        &f
                    chat: |-
                        &f
                        &a&lWelcome %PLAYER_NAME%!
                        &aYou has logged by non-premium account!
                        &f
                captcha: '&eYour captcha is &6%CAPTCHA%'
                premium: '&a&lDetected premium! &aIf you have premium launcher and want to auto login your account, please execute /autologin! &cDo not execute this command on the cracked launcher!'
                error:
                    timeout: '&c&lTimeout! &cJoin to the server and try again!'
                    registered: '&c&lRegistered! &cYou are already registered!'
                    enter-passwords: '&c&lInvalid arguments! &cEnter password, re-password, captcha and try again!'
                    password-too-short: '&c&lInvalid password! &cEnter longer password!'
                    password-too-long: '&c&lInvalid password! &cEnter shorter password!'
                    password-bad: '&c&lInvalid password! &cEnter better password!'
                    passwords-same: '&c&lInvalid passwords! &cPassword are not same!'
                    incorrect-captcha: '&c&lIncorrect captcha! &cEnter correct captcha and try again!'
            unregister:
                after: '&a&lUnregistered! &aYou have been unregistered!'
                error:
                    registered: '&c&lRegistered! &cYou are not registered!'
                    logged: '&c&lLogged! &cYou are not logged!'
                    premium: '&c&lYou are Premium &cYou can not unregister premium account!'
                    enter-password: '&c&lInvalid arguments! &cEnter password and try again!'
                    incorrect-password: '&c&lIncorrect password! &cEnter correct password and try again!'
            auto-login:
                after:
                    premium: '&a&lAuto Login! &aYou do not need use password to login!'
                    password: '&a&lAuto Login! &aYou need use password to login!'
                error:
                    premium: '&c&lYou are not Premium &cYou can not auto login non-premium account!'
                    disable-auto-login: '&c&lDisabled! &cYou could not to disable auto login!'
                    enter-passwords: '&c&lInvalid arguments! &cEnter password, re-password and try again!'
                    password-too-short: '&c&lInvalid password! &cEnter longer password!'
                    password-too-long: '&c&lInvalid password! &cEnter shorter password!'
                    password-bad: '&c&lInvalid password! &cEnter better password!'
                    passwords-same: '&c&lInvalid passwords! &cPassword are not same!'
            change-password:
                after:
                    fadeIn: 1
                    stay: 3
                    fadeOut: 1
                    title: '&a&lSuccessful!'
                    subtitle: '&aYour password has been changed!'
                    header: |-
                        &f
                        &a&lWelcome %PLAYER_NAME%!
                        &f
                    footer: |-
                        &f
                        &aYour password has been changed!
                        &f
                    chat: ''
                error:
                    registred: '&c&lRegistered! &cYou are not registered!'
                    logged: '&c&lLogged! &cYou are not logged!'
                    premium: '&c&lYou are Premium &cYou can not change password for premium account!'
                    enter-passwords: '&c&lInvalid arguments! &cEnter old password, password, re-password and try again!'
                    incorrect-old-password: '&c&lInvalid old password! &cEnter old password na try again!'
                    passwords-same: '&c&lInvalid passwords! &cPassword are not same!'
            change-language:
                after:
                    fadeIn: 1
                    stay: 3
                    fadeOut: 1
                    title: '&a&lSuccessful!'
                    subtitle: '&aYour language has been changed!'
                    header: |-
                        &f
                        &a&lWelcome %PLAYER_NAME%!
                        &f
                    footer: |-
                        &f
                        &aYour language has been changed!
                        &f
                    chat: ''
                error:
                    registred: '&c&lRegistered! &cYou are not registered!'
                    logged: '&c&lLogged! &cYou are not logged!'
                    enter-language: '&c&lInvalid arguments! &cEnter language!'
                    incorrect-language: '&c&lInvalid language! &cEnter correct language!'
            jpremium-register:
                after: '&a&lRegistered! &aYou have been registered new player!'
                error:
                    registered: '&c&lRegistered! &cYou are not registered!'
                    logged: '&c&lLogged! &cYou are not logged!'
                    enter-nickname-and-password: '&c&lInvalid arguments! &cEnter player nickname and password!'
                    user-is-premium: '&c&lUser is Premium! &cThis user is premium player!'
                    user-is-exist: '&c&lUser is exist! &cThis user is already exist!'
            jpremium-unregister:
                after:
                    user-kick: '&a&lUnregistered &aYou have been unregistered!'
                    unregistered: '&a&lUnregistered &aUser has been unregistered!'
                error:
                    registered: '&c&lRegistered! &cYou are not registered!'
                    logged: '&c&lLogged! &cYou are not logged!'
                    enter-nickname: '&c&lInvalid arguments! &cEnter player nickname!'
                    user-is-not-exist: '&c&lUser is not exist! &cThis user is not exist!'
                    user-is-premium: '&c&lUser is Premium! &cThis user is premium player!'
                    user-is-not-registered: '&c&lUser is not registered! &cThis user is not registered!'
            jpremium-change-password:
                after:
                    user-kick: '&a&lPassword Changed! &aYour password has been changed!'
                    password-changed: '&a&lPassword Changed! &aPassword has been changed!'
                error:
                    registered: '&c&lRegistered! &cYou are not registered!'
                    logged: '&c&lLogged! &cYou are not logged!'
                    enter-nickname-and-password: '&c&lInvalid arguments! &cEnter player nickname and password!'
                    user-is-not-exist: '&c&lUser is not exist! &cThis user is not exist!'
                    user-is-premium: '&c&lUser is Premium! &cThis user is premium player!'
                    user-is-not-registered: '&c&lUser is not registered! &cThis user is not registered!'
            jpremium-change-language:
                after:
                    user-changed:
                        fadeIn: 1
                        stay: 3
                        fadeOut: 1
                        title: '&a&lSuccessful!'
                        subtitle: '&aYour language has been changed!'
                        header: |-
                            &f
                            &a&lWelcome %PLAYER_NAME%!
                            &f
                        footer: |-
                            &f
                            &aYour language has been changed!
                            &f
                        chat: ''
                    language-changed: '&a&lLanguage Changed! &aLanguage has been changed!'
                error:
                    registred: '&c&lRegistered! &cYou are not registered!'
                    logged: '&c&lLogged! &cYou are not logged!'
                    enter-nickname-and-language: '&c&lInvalid arguments! &cEnter nickname and language!'
                    user-is-not-exist: '&c&lUser is not exist! &cThis user is not exist!'
                    incorrect-language: '&c&lInvalid language! &cEnter correct language!'
            jpremium-verify:
                  after:
                      premium: '&a&lPremium &aThis user is premium!'
                      non-premium: '&a&lNon-Premium &aThis user is non-premium!'
                  error:
                      registered: '&c&lRegistered! &cYou are not registered!'
                      logged: '&c&lLogged! &cYou are not logged!'
                      enter-nickname: '&c&lInvalid arguments! &cEnter player nickname!'
                      user-is-not-exist: '&c&lUser is not exist! &cThis user is not exist in JPremium database!'
