[...]
servers:
    lobby: #BungeeCord server name
        motd: 'Lobby server'
        address: localhost:25565
        restricted: false
    register: #BungeeCord server name
        motd: 'Login server'
        address: localhost:25566
        restricted: false
    login: #BungeeCord server name
        motd: 'Login server'
        address: localhost:25567
        restricted: false
[...]
